// Copyright © 2022-2023 Obol Labs Inc. Licensed under the terms of a Business Source License 1.1

// Code generated by "stringer -type=OrderStart -trimprefix=Start"; DO NOT EDIT.

package lifecycle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StartTracker-0]
	_ = x[StartPrivkeyLock-1]
	_ = x[StartAggSigDB-2]
	_ = x[StartRelay-3]
	_ = x[StartMonitoringAPI-4]
	_ = x[StartValidatorAPI-5]
	_ = x[StartP2PPing-6]
	_ = x[StartP2PRouters-7]
	_ = x[StartP2PConsensus-8]
	_ = x[StartSimulator-9]
	_ = x[StartScheduler-10]
	_ = x[StartP2PEventCollector-11]
	_ = x[StartPeerInfo-12]
	_ = x[StartParSigDB-13]
}

const _OrderStart_name = "TrackerPrivkeyLockAggSigDBRelayMonitoringAPIValidatorAPIP2PPingP2PRoutersP2PConsensusSimulatorSchedulerP2PEventCollectorPeerInfoParSigDB"

var _OrderStart_index = [...]uint8{0, 7, 18, 26, 31, 44, 56, 63, 73, 85, 94, 103, 120, 128, 136}

func (i OrderStart) String() string {
	if i < 0 || i >= OrderStart(len(_OrderStart_index)-1) {
		return "OrderStart(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderStart_name[_OrderStart_index[i]:_OrderStart_index[i+1]]
}
