// Copyright © 2022-2026 Obol Labs Inc. Licensed under the terms of a Business Source License 1.1

// Code generated by "stringer -type=OrderStart -trimprefix=Start"; DO NOT EDIT.

package lifecycle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StartTracker-0]
	_ = x[StartPrivkeyLock-1]
	_ = x[StartEth1Client-2]
	_ = x[StartAggSigDB-3]
	_ = x[StartRelay-4]
	_ = x[StartMonitoringAPI-5]
	_ = x[StartDebugAPI-6]
	_ = x[StartValidatorAPI-7]
	_ = x[StartP2PPing-8]
	_ = x[StartP2PRouters-9]
	_ = x[StartForceDirectConns-10]
	_ = x[StartForceQUICConns-11]
	_ = x[StartP2PConsensus-12]
	_ = x[StartSimulator-13]
	_ = x[StartScheduler-14]
	_ = x[StartBuilderRegWatcher-15]
	_ = x[StartP2PEventCollector-16]
	_ = x[StartPeerInfo-17]
	_ = x[StartParSigDB-18]
	_ = x[StartStackSnipe-19]
}

const _OrderStart_name = "TrackerPrivkeyLockEth1ClientAggSigDBRelayMonitoringAPIDebugAPIValidatorAPIP2PPingP2PRoutersForceDirectConnsForceQUICConnsP2PConsensusSimulatorSchedulerBuilderRegWatcherP2PEventCollectorPeerInfoParSigDBStackSnipe"

var _OrderStart_index = [...]uint8{0, 7, 18, 28, 36, 41, 54, 62, 74, 81, 91, 107, 121, 133, 142, 151, 168, 185, 193, 201, 211}

func (i OrderStart) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OrderStart_index)-1 {
		return "OrderStart(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderStart_name[_OrderStart_index[idx]:_OrderStart_index[idx+1]]
}
