// Copyright © 2022-2024 Obol Labs Inc. Licensed under the terms of a Business Source License 1.1

// Code generated by "stringer -type=OrderStop -trimprefix=Stop"; DO NOT EDIT.

package lifecycle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StopScheduler-0]
	_ = x[StopPrivkeyLock-1]
	_ = x[StopRetryer-2]
	_ = x[StopDutyDB-3]
	_ = x[StopBeaconMock-4]
	_ = x[StopValidatorAPI-5]
	_ = x[StopGenericSignature-6]
	_ = x[StopTracing-7]
	_ = x[StopP2PPeerDB-8]
	_ = x[StopP2PTCPNode-9]
	_ = x[StopP2PUDPNode-10]
	_ = x[StopDebugAPI-11]
	_ = x[StopMonitoringAPI-12]
}

const _OrderStop_name = "SchedulerPrivkeyLockRetryerDutyDBBeaconMockValidatorAPIGenericSignatureTracingP2PPeerDBP2PTCPNodeP2PUDPNodeDebugAPIMonitoringAPI"

var _OrderStop_index = [...]uint8{0, 9, 20, 27, 33, 43, 55, 71, 78, 87, 97, 107, 115, 128}

func (i OrderStop) String() string {
	if i < 0 || i >= OrderStop(len(_OrderStop_index)-1) {
		return "OrderStop(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderStop_name[_OrderStop_index[i]:_OrderStop_index[i+1]]
}
