version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
  - dependency-name: "github.com/herumi/bls-eth-go-binary"
    update-types: ["version-update:semver-major","version-update:semver-minor"]
  groups:
    go-dependencies:
      patterns:
        - "*"
- package-ecosystem: "docker"
  directories:
    - "/"
    - "/testutil/promrated/"
  schedule:
    interval: "daily"
  groups:
    docker-dependencies:
      patterns:
        - "*"
