version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directories:
    - "/"
    - "/testutil/promrated/"
    - "/testutil/compose/static/vouch/"
    - "/testutil/compose/static/lodestar/"
    - "/testutil/compose/static/lighthouse/"
  schedule:
    interval: "daily"
