run:
  timeout: 5m
linters-settings:
  cyclop:
    max-complexity: 15
    skip-tests: true
  forbidigo:
    forbid:
      - 'fmt\.Print.*'            # Prevent debug logging
  gci:
    local-prefixes: github.com/obolnetwork/charon
  gocritic:
    disabled-checks:
      - ifElseChain
  govet:
    enable-all: true
    disable:
      - fieldalignment
  nlreturn:
    block-size: 2
  revive:
    enable-all-rules: true
    severity: warning
    rules:
      # Disabled revive rules
      - name: banned-characters
        disabled: true
      - name: add-constant
        disabled: true
      - name: file-header
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: argument-limit
        disabled: true
      - name: function-length
        disabled: true

      # Some configured revive rules
      - name: cognitive-complexity
        arguments: [20]
      - name: imports-blacklist
        arguments: ["errors", "github.com/pkg/errors"] # Prefer ./app/errors
  staticcheck:
    go: "1.17"
    checks:
     - "all"
     - "-SA1019" # Ignoring since github.com/drand/kyber/sign/bls uses Proof Of Possession as does Ethereum.
  testpackage:
    skip-regexp: internal_test\.go
  wrapcheck:
    ignoreSigs:
      - github.com/obolnetwork/charon/

issues:
  fix: true
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - bodyclose
        - noctx
        - revive
        - gosec
  exclude:
    - "error returned from interface method should be wrapped" # Relax wrapcheck
    - "defer: prefer not to defer chains of function calls" # Relax revive
    - "avoid control coupling" # Relax revive
    - "shadow: declaration of \"err\" shadows declaration" # Relax govet

linters:
  enable-all: true
  disable:
    # Keep disabled
    - containedctx
    - exhaustivestruct
    - funlen
    - forcetypeassert
    - gochecknoglobals
    - godox
    - goerr113
    - golint
    - gomnd
    - gomoddirectives
    - ifshort
    - interfacer
    - ireturn
    - lll # Think about adding this (max line length)
    - maligned
    - paralleltest
    - prealloc
    - scopelint
    - tagliatelle
    - varnamelen
    - wsl
