linters-settings:
  cyclop:
    max-complexity: 15
    skip-tests: true
  gci:
    local-prefixes: github.com/obolnetwork/charon
  gocritic:
    disabled-checks:
      - ifElseChain
  nlreturn:
    block-size: 2
  staticcheck:
    go: "1.17"
    checks:
     - "all"
     - "-SA1019" # Ignoring since github.com/drand/kyber/sign/bls uses Proof Of Possession as does Ethereum.
  testpackage:
    skip-regexp: internal_test\.go
  whitespace:
    multi-if: true
    multi-func: true
  wsl:
    strict-append: false
    allow-assign-and-anything: true
    allow-separated-leading-comment: true
    allow-case-trailing-whitespace: true
    enforce-err-cuddling: true

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - bodyclose
        - noctx
  exclude:
    # Relax wsl and whitespace linters
    - "unnecessary leading newline"
    - "block should not start with a whitespace"
    - "only one cuddle assignment"
    - "only cuddled expressions if assigning variable or using from line above"

linters:
  enable-all: true
  disable:
    # Keep disabled
    - containedctx
    - exhaustivestruct
    - funlen
    - forcetypeassert
    - gochecknoglobals
    - godox
    - goerr113
    - gofumpt
    - golint
    - gomnd
    - gomoddirectives
    - ifshort
    - interfacer
    - ireturn
    - lll # Think about adding this (max line length)
    - maligned
    - paralleltest
    - scopelint
    - tagliatelle
    - varnamelen
    - wrapcheck
