coverage:
  status:
    project:
      default:
        branches: [main]
        informational: true
    patch:
      default:
        only_pulls: true # No patch status on single commits in main.
        informational: true
ignore:
  - "**/*_test.go"
  - "testutil"
