// Copyright © 2022-2024 Obol Labs Inc. Licensed under the terms of a Business Source License 1.1

// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	v1 "github.com/obolnetwork/charon/core/corepb/v1"
	mock "github.com/stretchr/testify/mock"
)

// Debugger is an autogenerated mock type for the Debugger type
type Debugger struct {
	mock.Mock
}

// AddInstance provides a mock function with given fields: instance
func (_m *Debugger) AddInstance(instance *v1.SniffedConsensusInstance) {
	_m.Called(instance)
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *Debugger) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// NewDebugger creates a new instance of Debugger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDebugger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Debugger {
	mock := &Debugger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
