// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dkg/dkgpb/v1/configsigs.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EIP712 signatures
type MsgConfigSig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CreatorConfigSig  []byte                 `protobuf:"bytes,1,opt,name=creator_config_sig,json=creatorConfigSig,proto3" json:"creator_config_sig,omitempty"`
	OperatorConfigSig []byte                 `protobuf:"bytes,2,opt,name=operator_config_sig,json=operatorConfigSig,proto3" json:"operator_config_sig,omitempty"`
	OperatorEnrSig    []byte                 `protobuf:"bytes,3,opt,name=operator_enr_sig,json=operatorEnrSig,proto3" json:"operator_enr_sig,omitempty"`
	PeerIndex         uint32                 `protobuf:"varint,4,opt,name=peer_index,json=peerIndex,proto3" json:"peer_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MsgConfigSig) Reset() {
	*x = MsgConfigSig{}
	mi := &file_dkg_dkgpb_v1_configsigs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgConfigSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgConfigSig) ProtoMessage() {}

func (x *MsgConfigSig) ProtoReflect() protoreflect.Message {
	mi := &file_dkg_dkgpb_v1_configsigs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgConfigSig.ProtoReflect.Descriptor instead.
func (*MsgConfigSig) Descriptor() ([]byte, []int) {
	return file_dkg_dkgpb_v1_configsigs_proto_rawDescGZIP(), []int{0}
}

func (x *MsgConfigSig) GetCreatorConfigSig() []byte {
	if x != nil {
		return x.CreatorConfigSig
	}
	return nil
}

func (x *MsgConfigSig) GetOperatorConfigSig() []byte {
	if x != nil {
		return x.OperatorConfigSig
	}
	return nil
}

func (x *MsgConfigSig) GetOperatorEnrSig() []byte {
	if x != nil {
		return x.OperatorEnrSig
	}
	return nil
}

func (x *MsgConfigSig) GetPeerIndex() uint32 {
	if x != nil {
		return x.PeerIndex
	}
	return 0
}

var File_dkg_dkgpb_v1_configsigs_proto protoreflect.FileDescriptor

const file_dkg_dkgpb_v1_configsigs_proto_rawDesc = "" +
	"\n" +
	"\x1ddkg/dkgpb/v1/configsigs.proto\x12\fdkg.dkgpb.v1\"\xb5\x01\n" +
	"\fMsgConfigSig\x12,\n" +
	"\x12creator_config_sig\x18\x01 \x01(\fR\x10creatorConfigSig\x12.\n" +
	"\x13operator_config_sig\x18\x02 \x01(\fR\x11operatorConfigSig\x12(\n" +
	"\x10operator_enr_sig\x18\x03 \x01(\fR\x0eoperatorEnrSig\x12\x1d\n" +
	"\n" +
	"peer_index\x18\x04 \x01(\rR\tpeerIndexB,Z*github.com/obolnetwork/charon/dkg/dkgpb/v1b\x06proto3"

var (
	file_dkg_dkgpb_v1_configsigs_proto_rawDescOnce sync.Once
	file_dkg_dkgpb_v1_configsigs_proto_rawDescData []byte
)

func file_dkg_dkgpb_v1_configsigs_proto_rawDescGZIP() []byte {
	file_dkg_dkgpb_v1_configsigs_proto_rawDescOnce.Do(func() {
		file_dkg_dkgpb_v1_configsigs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dkg_dkgpb_v1_configsigs_proto_rawDesc), len(file_dkg_dkgpb_v1_configsigs_proto_rawDesc)))
	})
	return file_dkg_dkgpb_v1_configsigs_proto_rawDescData
}

var file_dkg_dkgpb_v1_configsigs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dkg_dkgpb_v1_configsigs_proto_goTypes = []any{
	(*MsgConfigSig)(nil), // 0: dkg.dkgpb.v1.MsgConfigSig
}
var file_dkg_dkgpb_v1_configsigs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dkg_dkgpb_v1_configsigs_proto_init() }
func file_dkg_dkgpb_v1_configsigs_proto_init() {
	if File_dkg_dkgpb_v1_configsigs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dkg_dkgpb_v1_configsigs_proto_rawDesc), len(file_dkg_dkgpb_v1_configsigs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dkg_dkgpb_v1_configsigs_proto_goTypes,
		DependencyIndexes: file_dkg_dkgpb_v1_configsigs_proto_depIdxs,
		MessageInfos:      file_dkg_dkgpb_v1_configsigs_proto_msgTypes,
	}.Build()
	File_dkg_dkgpb_v1_configsigs_proto = out.File
	file_dkg_dkgpb_v1_configsigs_proto_goTypes = nil
	file_dkg_dkgpb_v1_configsigs_proto_depIdxs = nil
}
