// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dkg/dkgpb/v1/nodesigs.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgNodeSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	PeerIndex     uint32                 `protobuf:"varint,2,opt,name=peer_index,json=peerIndex,proto3" json:"peer_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgNodeSig) Reset() {
	*x = MsgNodeSig{}
	mi := &file_dkg_dkgpb_v1_nodesigs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgNodeSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgNodeSig) ProtoMessage() {}

func (x *MsgNodeSig) ProtoReflect() protoreflect.Message {
	mi := &file_dkg_dkgpb_v1_nodesigs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgNodeSig.ProtoReflect.Descriptor instead.
func (*MsgNodeSig) Descriptor() ([]byte, []int) {
	return file_dkg_dkgpb_v1_nodesigs_proto_rawDescGZIP(), []int{0}
}

func (x *MsgNodeSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *MsgNodeSig) GetPeerIndex() uint32 {
	if x != nil {
		return x.PeerIndex
	}
	return 0
}

type MsgOperatorSig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CreatorSignature []byte                 `protobuf:"bytes,1,opt,name=creator_signature,json=creatorSignature,proto3" json:"creator_signature,omitempty"`
	ConfigSignature  []byte                 `protobuf:"bytes,2,opt,name=config_signature,json=configSignature,proto3" json:"config_signature,omitempty"`
	EnrSignature     []byte                 `protobuf:"bytes,3,opt,name=enr_signature,json=enrSignature,proto3" json:"enr_signature,omitempty"`
	PeerIndex        uint32                 `protobuf:"varint,4,opt,name=peer_index,json=peerIndex,proto3" json:"peer_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MsgOperatorSig) Reset() {
	*x = MsgOperatorSig{}
	mi := &file_dkg_dkgpb_v1_nodesigs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgOperatorSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgOperatorSig) ProtoMessage() {}

func (x *MsgOperatorSig) ProtoReflect() protoreflect.Message {
	mi := &file_dkg_dkgpb_v1_nodesigs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgOperatorSig.ProtoReflect.Descriptor instead.
func (*MsgOperatorSig) Descriptor() ([]byte, []int) {
	return file_dkg_dkgpb_v1_nodesigs_proto_rawDescGZIP(), []int{1}
}

func (x *MsgOperatorSig) GetCreatorSignature() []byte {
	if x != nil {
		return x.CreatorSignature
	}
	return nil
}

func (x *MsgOperatorSig) GetConfigSignature() []byte {
	if x != nil {
		return x.ConfigSignature
	}
	return nil
}

func (x *MsgOperatorSig) GetEnrSignature() []byte {
	if x != nil {
		return x.EnrSignature
	}
	return nil
}

func (x *MsgOperatorSig) GetPeerIndex() uint32 {
	if x != nil {
		return x.PeerIndex
	}
	return 0
}

var File_dkg_dkgpb_v1_nodesigs_proto protoreflect.FileDescriptor

const file_dkg_dkgpb_v1_nodesigs_proto_rawDesc = "" +
	"\n" +
	"\x1bdkg/dkgpb/v1/nodesigs.proto\x12\fdkg.dkgpb.v1\"I\n" +
	"\n" +
	"MsgNodeSig\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"peer_index\x18\x02 \x01(\rR\tpeerIndex\"\xac\x01\n" +
	"\x0eMsgOperatorSig\x12+\n" +
	"\x11creator_signature\x18\x01 \x01(\fR\x10creatorSignature\x12)\n" +
	"\x10config_signature\x18\x02 \x01(\fR\x0fconfigSignature\x12#\n" +
	"\renr_signature\x18\x03 \x01(\fR\fenrSignature\x12\x1d\n" +
	"\n" +
	"peer_index\x18\x04 \x01(\rR\tpeerIndexB,Z*github.com/obolnetwork/charon/dkg/dkgpb/v1b\x06proto3"

var (
	file_dkg_dkgpb_v1_nodesigs_proto_rawDescOnce sync.Once
	file_dkg_dkgpb_v1_nodesigs_proto_rawDescData []byte
)

func file_dkg_dkgpb_v1_nodesigs_proto_rawDescGZIP() []byte {
	file_dkg_dkgpb_v1_nodesigs_proto_rawDescOnce.Do(func() {
		file_dkg_dkgpb_v1_nodesigs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dkg_dkgpb_v1_nodesigs_proto_rawDesc), len(file_dkg_dkgpb_v1_nodesigs_proto_rawDesc)))
	})
	return file_dkg_dkgpb_v1_nodesigs_proto_rawDescData
}

var file_dkg_dkgpb_v1_nodesigs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dkg_dkgpb_v1_nodesigs_proto_goTypes = []any{
	(*MsgNodeSig)(nil),     // 0: dkg.dkgpb.v1.MsgNodeSig
	(*MsgOperatorSig)(nil), // 1: dkg.dkgpb.v1.MsgOperatorSig
}
var file_dkg_dkgpb_v1_nodesigs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dkg_dkgpb_v1_nodesigs_proto_init() }
func file_dkg_dkgpb_v1_nodesigs_proto_init() {
	if File_dkg_dkgpb_v1_nodesigs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dkg_dkgpb_v1_nodesigs_proto_rawDesc), len(file_dkg_dkgpb_v1_nodesigs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dkg_dkgpb_v1_nodesigs_proto_goTypes,
		DependencyIndexes: file_dkg_dkgpb_v1_nodesigs_proto_depIdxs,
		MessageInfos:      file_dkg_dkgpb_v1_nodesigs_proto_msgTypes,
	}.Build()
	File_dkg_dkgpb_v1_nodesigs_proto = out.File
	file_dkg_dkgpb_v1_nodesigs_proto_goTypes = nil
	file_dkg_dkgpb_v1_nodesigs_proto_depIdxs = nil
}
