// Copyright © 2022 Obol Labs Inc.
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// You should have received a copy of the GNU General Public License along with
// this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by "stringer -type=component"; DO NOT EDIT.

package tracker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[zero-0]
	_ = x[scheduler-1]
	_ = x[fetcher-2]
	_ = x[consensus-3]
	_ = x[validatorAPI-4]
	_ = x[parSigDBInternal-5]
	_ = x[parSigEx-6]
	_ = x[parSigDBThreshold-7]
	_ = x[sigAgg-8]
	_ = x[sentinel-9]
}

const _component_name = "zeroschedulerfetcherconsensusvalidatorAPIparSigDBInternalparSigExparSigDBThresholdsigAggsentinel"

var _component_index = [...]uint8{0, 4, 13, 20, 29, 41, 57, 65, 82, 88, 96}

func (i component) String() string {
	if i < 0 || i >= component(len(_component_index)-1) {
		return "component(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _component_name[_component_index[i]:_component_index[i+1]]
}
