name: Setup go

outputs:
  go-version:
    description: "The Go version that was set up"
    value: ${{ steps.setup-go.outputs.go-version }}

runs:
  using: "composite"
  steps:
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"
