// Copyright © 2022-2024 Obol Labs Inc. Licensed under the terms of a Business Source License 1.1

// Code generated by "stringer -type=status -trimprefix=status"; DO NOT EDIT.

package featureset

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[statusAlpha-1]
	_ = x[statusBeta-2]
	_ = x[statusStable-3]
}

const _status_name = "AlphaBetaStable"

var _status_index = [...]uint8{0, 5, 9, 15}

func (i status) String() string {
	i -= 1
	if i < 0 || i >= status(len(_status_index)-1) {
		return "status(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _status_name[_status_index[i]:_status_index[i+1]]
}
