// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: app/protonil/testdata/v1/test.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type M1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	M2            *M2                    `protobuf:"bytes,2,opt,name=m2,proto3" json:"m2,omitempty"`
	M2Optional    *M2                    `protobuf:"bytes,3,opt,name=m2_optional,json=m2Optional,proto3,oneof" json:"m2_optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M1) Reset() {
	*x = M1{}
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M1) ProtoMessage() {}

func (x *M1) ProtoReflect() protoreflect.Message {
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M1.ProtoReflect.Descriptor instead.
func (*M1) Descriptor() ([]byte, []int) {
	return file_app_protonil_testdata_v1_test_proto_rawDescGZIP(), []int{0}
}

func (x *M1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *M1) GetM2() *M2 {
	if x != nil {
		return x.M2
	}
	return nil
}

func (x *M1) GetM2Optional() *M2 {
	if x != nil {
		return x.M2Optional
	}
	return nil
}

type M2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	M3            *M3                    `protobuf:"bytes,2,opt,name=m3,proto3" json:"m3,omitempty"`
	M3Optional    *M3                    `protobuf:"bytes,3,opt,name=m3_optional,json=m3Optional,proto3,oneof" json:"m3_optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2) Reset() {
	*x = M2{}
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2) ProtoMessage() {}

func (x *M2) ProtoReflect() protoreflect.Message {
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2.ProtoReflect.Descriptor instead.
func (*M2) Descriptor() ([]byte, []int) {
	return file_app_protonil_testdata_v1_test_proto_rawDescGZIP(), []int{1}
}

func (x *M2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *M2) GetM3() *M3 {
	if x != nil {
		return x.M3
	}
	return nil
}

func (x *M2) GetM3Optional() *M3 {
	if x != nil {
		return x.M3Optional
	}
	return nil
}

type M3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Note it doesn't start at 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M3) Reset() {
	*x = M3{}
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M3) ProtoMessage() {}

func (x *M3) ProtoReflect() protoreflect.Message {
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M3.ProtoReflect.Descriptor instead.
func (*M3) Descriptor() ([]byte, []int) {
	return file_app_protonil_testdata_v1_test_proto_rawDescGZIP(), []int{2}
}

func (x *M3) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type M4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	M3Map         map[string]*M3         `protobuf:"bytes,2,rep,name=m3_map,json=m3Map,proto3" json:"m3_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	M3List        []*M3                  `protobuf:"bytes,3,rep,name=m3_list,json=m3List,proto3" json:"m3_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M4) Reset() {
	*x = M4{}
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M4) ProtoMessage() {}

func (x *M4) ProtoReflect() protoreflect.Message {
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M4.ProtoReflect.Descriptor instead.
func (*M4) Descriptor() ([]byte, []int) {
	return file_app_protonil_testdata_v1_test_proto_rawDescGZIP(), []int{3}
}

func (x *M4) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *M4) GetM3Map() map[string]*M3 {
	if x != nil {
		return x.M3Map
	}
	return nil
}

func (x *M4) GetM3List() []*M3 {
	if x != nil {
		return x.M3List
	}
	return nil
}

// MaxIndex is used to test the max index
type MaxIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,65,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxIndex) Reset() {
	*x = MaxIndex{}
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxIndex) ProtoMessage() {}

func (x *MaxIndex) ProtoReflect() protoreflect.Message {
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxIndex.ProtoReflect.Descriptor instead.
func (*MaxIndex) Descriptor() ([]byte, []int) {
	return file_app_protonil_testdata_v1_test_proto_rawDescGZIP(), []int{4}
}

func (x *MaxIndex) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Attack is a weird message that extends M1
// and adds a unknown field and a invalid numbered field.
// Both should be ignored.
type Attack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	M2            *M2                    `protobuf:"bytes,2,opt,name=m2,proto3" json:"m2,omitempty"`
	M2Optional    *M2                    `protobuf:"bytes,3,opt,name=m2_optional,json=m2Optional,proto3,oneof" json:"m2_optional,omitempty"`
	M3Unknown     *M3                    `protobuf:"bytes,4,opt,name=m3_unknown,json=m3Unknown,proto3" json:"m3_unknown,omitempty"`
	M3Attack      *M3                    `protobuf:"bytes,99999999,opt,name=m3_attack,json=m3Attack,proto3" json:"m3_attack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attack) Reset() {
	*x = Attack{}
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attack) ProtoMessage() {}

func (x *Attack) ProtoReflect() protoreflect.Message {
	mi := &file_app_protonil_testdata_v1_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attack.ProtoReflect.Descriptor instead.
func (*Attack) Descriptor() ([]byte, []int) {
	return file_app_protonil_testdata_v1_test_proto_rawDescGZIP(), []int{5}
}

func (x *Attack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attack) GetM2() *M2 {
	if x != nil {
		return x.M2
	}
	return nil
}

func (x *Attack) GetM2Optional() *M2 {
	if x != nil {
		return x.M2Optional
	}
	return nil
}

func (x *Attack) GetM3Unknown() *M3 {
	if x != nil {
		return x.M3Unknown
	}
	return nil
}

func (x *Attack) GetM3Attack() *M3 {
	if x != nil {
		return x.M3Attack
	}
	return nil
}

var File_app_protonil_testdata_v1_test_proto protoreflect.FileDescriptor

const file_app_protonil_testdata_v1_test_proto_rawDesc = "" +
	"\n" +
	"#app/protonil/testdata/v1/test.proto\x12\x18app.protonil.testdata.v1\"\x9a\x01\n" +
	"\x02M1\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x02m2\x18\x02 \x01(\v2\x1c.app.protonil.testdata.v1.M2R\x02m2\x12B\n" +
	"\vm2_optional\x18\x03 \x01(\v2\x1c.app.protonil.testdata.v1.M2H\x00R\n" +
	"m2Optional\x88\x01\x01B\x0e\n" +
	"\f_m2_optional\"\x9a\x01\n" +
	"\x02M2\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x02m3\x18\x02 \x01(\v2\x1c.app.protonil.testdata.v1.M3R\x02m3\x12B\n" +
	"\vm3_optional\x18\x03 \x01(\v2\x1c.app.protonil.testdata.v1.M3H\x00R\n" +
	"m3Optional\x88\x01\x01B\x0e\n" +
	"\f_m3_optional\"\x18\n" +
	"\x02M3\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xed\x01\n" +
	"\x02M4\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\x06m3_map\x18\x02 \x03(\v2'.app.protonil.testdata.v1.M4.M3MapEntryR\x05m3Map\x125\n" +
	"\am3_list\x18\x03 \x03(\v2\x1c.app.protonil.testdata.v1.M3R\x06m3List\x1aV\n" +
	"\n" +
	"M3MapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.app.protonil.testdata.v1.M3R\x05value:\x028\x01J\x04\b\x04\x10\x05\"\x1e\n" +
	"\bMaxIndex\x12\x12\n" +
	"\x04name\x18A \x01(\tR\x04name\"\x99\x02\n" +
	"\x06Attack\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x02m2\x18\x02 \x01(\v2\x1c.app.protonil.testdata.v1.M2R\x02m2\x12B\n" +
	"\vm2_optional\x18\x03 \x01(\v2\x1c.app.protonil.testdata.v1.M2H\x00R\n" +
	"m2Optional\x88\x01\x01\x12;\n" +
	"\n" +
	"m3_unknown\x18\x04 \x01(\v2\x1c.app.protonil.testdata.v1.M3R\tm3Unknown\x12<\n" +
	"\tm3_attack\x18\xff\xc1\xd7/ \x01(\v2\x1c.app.protonil.testdata.v1.M3R\bm3AttackB\x0e\n" +
	"\f_m2_optionalB8Z6github.com/obolnetwork/charon/app/protonil/testdata/v1b\x06proto3"

var (
	file_app_protonil_testdata_v1_test_proto_rawDescOnce sync.Once
	file_app_protonil_testdata_v1_test_proto_rawDescData []byte
)

func file_app_protonil_testdata_v1_test_proto_rawDescGZIP() []byte {
	file_app_protonil_testdata_v1_test_proto_rawDescOnce.Do(func() {
		file_app_protonil_testdata_v1_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_protonil_testdata_v1_test_proto_rawDesc), len(file_app_protonil_testdata_v1_test_proto_rawDesc)))
	})
	return file_app_protonil_testdata_v1_test_proto_rawDescData
}

var file_app_protonil_testdata_v1_test_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_protonil_testdata_v1_test_proto_goTypes = []any{
	(*M1)(nil),       // 0: app.protonil.testdata.v1.M1
	(*M2)(nil),       // 1: app.protonil.testdata.v1.M2
	(*M3)(nil),       // 2: app.protonil.testdata.v1.M3
	(*M4)(nil),       // 3: app.protonil.testdata.v1.M4
	(*MaxIndex)(nil), // 4: app.protonil.testdata.v1.MaxIndex
	(*Attack)(nil),   // 5: app.protonil.testdata.v1.Attack
	nil,              // 6: app.protonil.testdata.v1.M4.M3MapEntry
}
var file_app_protonil_testdata_v1_test_proto_depIdxs = []int32{
	1,  // 0: app.protonil.testdata.v1.M1.m2:type_name -> app.protonil.testdata.v1.M2
	1,  // 1: app.protonil.testdata.v1.M1.m2_optional:type_name -> app.protonil.testdata.v1.M2
	2,  // 2: app.protonil.testdata.v1.M2.m3:type_name -> app.protonil.testdata.v1.M3
	2,  // 3: app.protonil.testdata.v1.M2.m3_optional:type_name -> app.protonil.testdata.v1.M3
	6,  // 4: app.protonil.testdata.v1.M4.m3_map:type_name -> app.protonil.testdata.v1.M4.M3MapEntry
	2,  // 5: app.protonil.testdata.v1.M4.m3_list:type_name -> app.protonil.testdata.v1.M3
	1,  // 6: app.protonil.testdata.v1.Attack.m2:type_name -> app.protonil.testdata.v1.M2
	1,  // 7: app.protonil.testdata.v1.Attack.m2_optional:type_name -> app.protonil.testdata.v1.M2
	2,  // 8: app.protonil.testdata.v1.Attack.m3_unknown:type_name -> app.protonil.testdata.v1.M3
	2,  // 9: app.protonil.testdata.v1.Attack.m3_attack:type_name -> app.protonil.testdata.v1.M3
	2,  // 10: app.protonil.testdata.v1.M4.M3MapEntry.value:type_name -> app.protonil.testdata.v1.M3
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_app_protonil_testdata_v1_test_proto_init() }
func file_app_protonil_testdata_v1_test_proto_init() {
	if File_app_protonil_testdata_v1_test_proto != nil {
		return
	}
	file_app_protonil_testdata_v1_test_proto_msgTypes[0].OneofWrappers = []any{}
	file_app_protonil_testdata_v1_test_proto_msgTypes[1].OneofWrappers = []any{}
	file_app_protonil_testdata_v1_test_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_protonil_testdata_v1_test_proto_rawDesc), len(file_app_protonil_testdata_v1_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_protonil_testdata_v1_test_proto_goTypes,
		DependencyIndexes: file_app_protonil_testdata_v1_test_proto_depIdxs,
		MessageInfos:      file_app_protonil_testdata_v1_test_proto_msgTypes,
	}.Build()
	File_app_protonil_testdata_v1_test_proto = out.File
	file_app_protonil_testdata_v1_test_proto_goTypes = nil
	file_app_protonil_testdata_v1_test_proto_depIdxs = nil
}
