{
 "title": "Simnet",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "node0,node1,node2,node3" }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "Slot/Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_scheduler_current_slot{job=\"$node\"}",
     "legendFormat": "Slot"
    },
    {
     "expr": "core_scheduler_current_epoch{job=\"$node\"}",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Version Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(\n  sum(app_git_commit{job=\"$node\"}) by (git_hash)\n)\n   + on(job) group_left(version)\n(\n   0 * sum(app_version{job=\"$node\"}) by (version)\n)\n   + on(job) group_left(lock_hash)\n(\n   0 * sum(app_lock_hash{job=\"$node\"}) by (lock_hash)\n)"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "description": "Node is healthy if Beacon Node connected and synced and at least quorum peers are connected.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_monitoring_readyz{job=\"$node\"} "
    }
   ]
  },
  {
   "title": "# Validators Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_scheduler_validators_active{job=\"$node\"}"
    }
   ]
  },
  {
   "title": "# Peer Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(p2p_ping_success{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "# Relays Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(p2p_relay_connections{job=\"$node\"}) "
    }
   ]
  },
  {
   "title": "P2P Reachability",
   "type": "stat",
   "description": "Current libp2p reachability status of this node as detected by AutoNat.",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_reachability_status{job=\"$node\"}"
    }
   ]
  },
  {
   "title": "Voluntary Exits",
   "type": "stat",
   "description": "Number of partial signatures collected per voluntary exiting validator.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_parsigdb_exit_totalcore_{job=\"$node\"}) by (pubkey)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(p2p_ping_success{job=\"$node\"}) by (peer)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{job=\"$node\"}[30s])) by (le,peer))  * 1000"
    },
    {
     "expr": "sum(core_tracker_participation{job=\"$node\", duty=\"attester\"}) by (peer)"
    },
    {
     "expr": "sum(core_tracker_participation{job=\"$node\", duty=\"proposer\"}) by (peer)"
    },
    {
     "expr": "sum(core_tracker_participation{job=\"$node\", duty=\"randao\"}) by (peer)"
    },
    {
     "expr": "sum(p2p_ping_success{job=\"$node\"}) by (peer)"
    }
   ]
  },
  {
   "title": "Peer ping latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{job=\"$node\"}[30s])) by (le,peer))  ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Errors by topic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "increase(app_log_error_total{job=\"$node\"}[30s]) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Warnings by topic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "increase(app_log_warn_total{job=\"$node\"}[30s]) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Completed duties by type ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "increase(core_bcast_broadcast_total{job=\"$node\"}[30s]) ",
     "legendFormat": "{{duty}}"
    },
    {
     "expr": "increase(core_scheduler_current_epoch{job=\"$node\"}[30s]) * 0.2",
     "legendFormat": "epoch boundry"
    }
   ]
  },
  {
   "title": "Failed duties by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(core_tracker_failed_duties_total{job=\"$node\"}[30s])) by (duty)",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "Number of participating peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_tracker_participation{job=\"$node\"}) by (duty)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Beacon API requests rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(app_eth2_latency_seconds_count{job=\"$node\"}[30s]) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Beacon API request latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_eth2_latency_seconds_bucket[30s])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Validator API requests rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(core_validatorapi_request_latency_seconds_count{job=\"$node\"}[30s])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Validator API request latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(core_validatorapi_request_latency_seconds_bucket[30s])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$node\"}",
     "legendFormat": "Allocated Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$node\"}[$__rate_interval])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Go Routines and File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$node\"}",
     "legendFormat": "Go Routines"
    },
    {
     "expr": "process_open_fds{job=\"$node\"}",
     "legendFormat": "File Descriptors"
    }
   ]
  }
 ]
}