{
 "title": "Alerts",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Error Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(app_log_error_total[30s]) "
    }
   ]
  },
  {
   "title": "Warn Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "increase(app_log_warn_total[30s]) "
    }
   ]
  },
  {
   "title": "Validator API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(core_validatorapi_request_error_total{endpoint!=\"proxy\"}[30s]) "
    }
   ]
  },
  {
   "title": "Proxy API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "increase(core_validatorapi_request_error_total{endpoint=\"proxy\"}[30s]) "
    }
   ]
  },
  {
   "title": "Broadcast Duty Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(core_bcast_broadcast_total[30s])",
     "legendFormat": "{{job}} - {{type}}"
    }
   ]
  },
  {
   "title": "Outstanding Duty Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "core_bcast_broadcast_total - core_scheduler_duty_total",
     "legendFormat": "{{job}} - {{type}}"
    }
   ]
  }
 ]
}