apiVersion: 1

notifiers:
  - name: compose-webhook
    type: webhook
    uid: compose-webhook
    org_id: 1
    is_default: true
    send_reminder: false
    frequency: 1s
    disable_resolve_message: true
    settings:
      url: http://host.docker.internal:26354
      httpMethod: POST
