global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']

  - job_name: 'teku'
    static_configs:
    - targets: ['beacon:8008']

  - job_name: 'charon'
    static_configs:
    - targets: ['charon:8088']
  # - job_name: 'validator'
  #   static_configs:
  #   - targets: ['127.0.0.1:8081']

  # - job_name: 'lighthouse'
  #   static_configs:
  #   - targets: ['localhost:5054']

  - job_name: 'geth'
    static_configs:
    - targets: ['192.168.0.68:6060']
    metrics_path: '/debug/metrics/prometheus'
