// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: core/corepb/v1/core.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Duty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // uint64
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // core.DutyType
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duty) Reset() {
	*x = Duty{}
	mi := &file_core_corepb_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty) ProtoMessage() {}

func (x *Duty) ProtoReflect() protoreflect.Message {
	mi := &file_core_corepb_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty.ProtoReflect.Descriptor instead.
func (*Duty) Descriptor() ([]byte, []int) {
	return file_core_corepb_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Duty) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Duty) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type UnsignedDataSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           map[string][]byte      `protobuf:"bytes,1,rep,name=set,proto3" json:"set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[core.PubKey]core.UnsignedData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsignedDataSet) Reset() {
	*x = UnsignedDataSet{}
	mi := &file_core_corepb_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsignedDataSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsignedDataSet) ProtoMessage() {}

func (x *UnsignedDataSet) ProtoReflect() protoreflect.Message {
	mi := &file_core_corepb_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsignedDataSet.ProtoReflect.Descriptor instead.
func (*UnsignedDataSet) Descriptor() ([]byte, []int) {
	return file_core_corepb_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *UnsignedDataSet) GetSet() map[string][]byte {
	if x != nil {
		return x.Set
	}
	return nil
}

type ParSignedDataSet struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Set           map[string]*ParSignedData `protobuf:"bytes,1,rep,name=set,proto3" json:"set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[core.PubKey]core.ParSignedData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParSignedDataSet) Reset() {
	*x = ParSignedDataSet{}
	mi := &file_core_corepb_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParSignedDataSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParSignedDataSet) ProtoMessage() {}

func (x *ParSignedDataSet) ProtoReflect() protoreflect.Message {
	mi := &file_core_corepb_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParSignedDataSet.ProtoReflect.Descriptor instead.
func (*ParSignedDataSet) Descriptor() ([]byte, []int) {
	return file_core_corepb_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *ParSignedDataSet) GetSet() map[string]*ParSignedData {
	if x != nil {
		return x.Set
	}
	return nil
}

type ParSignedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                          // []byte
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                // core.Signature
	ShareIdx      int32                  `protobuf:"varint,3,opt,name=share_idx,json=shareIdx,proto3" json:"share_idx,omitempty"` // int
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParSignedData) Reset() {
	*x = ParSignedData{}
	mi := &file_core_corepb_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParSignedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParSignedData) ProtoMessage() {}

func (x *ParSignedData) ProtoReflect() protoreflect.Message {
	mi := &file_core_corepb_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParSignedData.ProtoReflect.Descriptor instead.
func (*ParSignedData) Descriptor() ([]byte, []int) {
	return file_core_corepb_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *ParSignedData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ParSignedData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ParSignedData) GetShareIdx() int32 {
	if x != nil {
		return x.ShareIdx
	}
	return 0
}

var File_core_corepb_v1_core_proto protoreflect.FileDescriptor

const file_core_corepb_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x19core/corepb/v1/core.proto\x12\x0ecore.corepb.v1\".\n" +
	"\x04Duty\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\"\x85\x01\n" +
	"\x0fUnsignedDataSet\x12:\n" +
	"\x03set\x18\x01 \x03(\v2(.core.corepb.v1.UnsignedDataSet.SetEntryR\x03set\x1a6\n" +
	"\bSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xa6\x01\n" +
	"\x10ParSignedDataSet\x12;\n" +
	"\x03set\x18\x01 \x03(\v2).core.corepb.v1.ParSignedDataSet.SetEntryR\x03set\x1aU\n" +
	"\bSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.core.corepb.v1.ParSignedDataR\x05value:\x028\x01\"^\n" +
	"\rParSignedData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1b\n" +
	"\tshare_idx\x18\x03 \x01(\x05R\bshareIdxB.Z,github.com/obolnetwork/charon/core/corepb/v1b\x06proto3"

var (
	file_core_corepb_v1_core_proto_rawDescOnce sync.Once
	file_core_corepb_v1_core_proto_rawDescData []byte
)

func file_core_corepb_v1_core_proto_rawDescGZIP() []byte {
	file_core_corepb_v1_core_proto_rawDescOnce.Do(func() {
		file_core_corepb_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_corepb_v1_core_proto_rawDesc), len(file_core_corepb_v1_core_proto_rawDesc)))
	})
	return file_core_corepb_v1_core_proto_rawDescData
}

var file_core_corepb_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_corepb_v1_core_proto_goTypes = []any{
	(*Duty)(nil),             // 0: core.corepb.v1.Duty
	(*UnsignedDataSet)(nil),  // 1: core.corepb.v1.UnsignedDataSet
	(*ParSignedDataSet)(nil), // 2: core.corepb.v1.ParSignedDataSet
	(*ParSignedData)(nil),    // 3: core.corepb.v1.ParSignedData
	nil,                      // 4: core.corepb.v1.UnsignedDataSet.SetEntry
	nil,                      // 5: core.corepb.v1.ParSignedDataSet.SetEntry
}
var file_core_corepb_v1_core_proto_depIdxs = []int32{
	4, // 0: core.corepb.v1.UnsignedDataSet.set:type_name -> core.corepb.v1.UnsignedDataSet.SetEntry
	5, // 1: core.corepb.v1.ParSignedDataSet.set:type_name -> core.corepb.v1.ParSignedDataSet.SetEntry
	3, // 2: core.corepb.v1.ParSignedDataSet.SetEntry.value:type_name -> core.corepb.v1.ParSignedData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_corepb_v1_core_proto_init() }
func file_core_corepb_v1_core_proto_init() {
	if File_core_corepb_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_corepb_v1_core_proto_rawDesc), len(file_core_corepb_v1_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_corepb_v1_core_proto_goTypes,
		DependencyIndexes: file_core_corepb_v1_core_proto_depIdxs,
		MessageInfos:      file_core_corepb_v1_core_proto_msgTypes,
	}.Build()
	File_core_corepb_v1_core_proto = out.File
	file_core_corepb_v1_core_proto_goTypes = nil
	file_core_corepb_v1_core_proto_depIdxs = nil
}
