name: Build and Release Binaries

on:
  workflow_run:
    workflows: ["Publish Release"]
    types:
      - completed

jobs:
  build-binaries:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/v')
    runs-on: ubuntu-24.04
    name: Build Cross-Platform Binaries
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: ./.github/actions/setup-go
      id: setup-go

    - name: Install cross-compilation dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Set up GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        install-only: true

    - name: Run GoReleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goreleaser release --clean
