name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"

      - name: Set up aarch64 gcc
        run: |
          sudo apt install gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: osxcross
        uses: Timmmm/setup-osxcross@main
        with:
          osx-version: "14.0"

      - name: Add osxcross binaries to path
        run: |
          echo "/home/runner/work/_actions/Timmmm/setup-osxcross/main/osxcross/target/bin" >> $GITHUB_PATH
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
