name: govulncheck
on:
  pull_request:
  push:
    branches:
      - main*

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-go
      - run: go install tool golang.org/x/vuln/cmd/govulncheck
      - run: govulncheck -show=traces -test ./...
