# This runs long wait DKG test once a day at 12:00 noon.
name: long wait dkg
on:
  schedule:
    - cron: '00 12 * * *'

jobs:
  nightly_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.3'
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go test -v -timeout=60m -race github.com/obolnetwork/charon/testutil/integration -long-wait
