name: 'Deploy Relay To Prod'

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: The docker image tag to deploy
        required: true
        type: string

jobs:
  deploy-relay:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
    - name: Trigger dev relay deploy job
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.CHARON_K8S_REPO_ACCESS_TOKEN }}
        repository: ObolNetwork/obol-infrastructure
        event-type: relay-prod-deployment
        client-payload: |
          '{
            "relay_name": "relay-0",
            "relay_version": "${{ github.image_tag }}"
          }'